import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

type Country = {
  name: {common: string}
  capital: string[]
};

let getCountries = function(){
  return fetch('https://restcountries.com/v3.1/all')
  .then(res => res.json())
  .then(countries => {
    return countries.sort(() => Math.random() - Math.random()).slice(0, 3) as Country[]
  })
}

getCountries();

const Home: NextPage = () => {
  // const [allCountries, setAllCountries] = useState([]);
  const [countriesSet, setCountriesSet] = useState<Country[]>([]);



  const evaluateAnswer = (country, currentCountry) => {
      if (country.name.common === currentCountry.name.common)
      {
        console.log("win");
        
      } else {
        console.log("lose");
        
      }
  }

  return (
    <>
      <div className={styles.main}>
        <h1 className={styles.title}>
          {countriesSet[0]?.name.common}
        </h1>
        <div>
          {
            countriesSet?.map(x => x).sort(() => Math.random() - Math.random()).map((country, index) => 
              <button key={index} onClick={() => evaluateAnswer(country, countriesSet[0])}>{country.capital[0]}</button>
            )
          }
        </div>
      </div>
    </>
  )
  // return (
  //   <>
  //     <Head>
  //       <title>Create T3 App</title>
  //       <meta name="description" content="Generated by create-t3-app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>
  //     <main className={styles.main}>
  //       <div className={styles.container}>
  //         <h1 className={styles.title}>
  //           Create <span className={styles.pinkSpan}>T3</span> App
  //         </h1>
  //         <div className={styles.cardRow}>
  //           <Link
  //             className={styles.card}
  //             href="https://create.t3.gg/en/usage/first-steps"
  //             target="_blank"
  //           >
  //             <h3 className={styles.cardTitle}>First Steps →</h3>
  //             <div className={styles.cardText}>
  //               Just the basics - Everything you need to know to set up your
  //               database and authentication.
  //             </div>
  //           </Link>
  //           <Link
  //             className={styles.card}
  //             href="https://create.t3.gg/en/introduction"
  //             target="_blank"
  //           >
  //             <h3 className={styles.cardTitle}>Documentation →</h3>
  //             <div className={styles.cardText}>
  //               Learn more about Create T3 App, the libraries it uses, and how
  //               to deploy it.
  //             </div>
  //           </Link>
  //         </div>
  //       </div>
  //     </main>
  //   </>
  // );
};

export default Home;
